// auth types
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';


// user types
export const SET_USER_INFO = 'SET_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';


// coin types
export const GET_COIN_LIST_PENDING = 'GET_COIN_LIST_PENDING';
export const GET_COIN_LIST_SUCCESS = 'GET_COIN_LIST_SUCCESS';
export const GET_COIN_LIST_FAILURE = 'GET_COIN_LIST_FAILURE';
export const SET_COIN_LIST = 'SET_COIN_LIST';


// portfolio types
export const GET_TYPES_PENDING = 'GET_TYPES_PENDING';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_FAILURE = 'GET_TYPES_FAILURE';

export const SAVE_PORTFOLIO_PENDING = 'SAVE_PORTFOLIO_PENDING';
export const SAVE_PORTFOLIO_SUCCESS = 'SAVE_PORTFOLIO_SUCCESS';
export const SAVE_PORTFOLIO_FAILURE = 'SAVE_PORTFOLIO_FAILURE';
